kind: pipeline
name: build

steps:

  - name: build
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - env
      - DOCKER_BUILDKIT=1 docker build --progress plain -t drone-server-local:${DRONE_COMMIT:0:6} -f Dockerfile .

  - name: test
    image: drone-server-local:${DRONE_COMMIT:0:6}
    commands:
      - echo run test
      - echo done
    depends_on:
      - build

  - name: final
    image: alpine
    commands:
      - echo run final
    depends_on:
      - build
      - test

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock