kind: pipeline
name: build

steps:
  - name: build
    image: alpine
    commands:
      - echo build code
      - sleep 10
      - echo done

  - name: test
    image: alpine
    commands:
      - echo run test
      - sleep 10
      - echo done

  - name: test2
    image: alpine
    commands:
      - echo run test2
      - sleep 10
      - echo done

  - name: test3
    image: alpine
    commands:
      - echo run test3
      - sleep 10
      - echo done

  - name: test4
    image: alpine
    commands:
      - echo run test4
      - sleep 10
      - echo fail
      - exit 1

  - name: test5
    image: alpine
    commands:
      - echo run test5
      - sleep 10
      - echo done

  - name: final
    image: alpine
    commands:
      - echo run final
    depends_on:
      - build
      - test
      - test2
      - test3
      - test4
      - test5