kind: pipeline
name: build

steps:
  - name: build
    image: alpine
    commands:
      - echo build code
      - sleep 10
      - echo done

  - name: test
    image: alpine
    commands:
      - echo run test
      - sleep 10
      - echo done

  - name: final
    image: alpine
    commands:
      - echo run final
    depends_on:
      - build
      - test